# C:\DevOps\30juneTest\.github\workflows\ci.yml
name: CI Pipeline

on:
  push:
    branches:
      - main # or master
  pull_request:
    branches:
      - main # or master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # --- NOTE THE FILE NAME CHANGE HERE ---
        pip install -r req.txt

    - name: Run a placeholder build step
      run: |
        echo "Simulating a build process..."
        echo "Build successful!"